"""Run the 5-minute demo flow through the copilot and write docs/demo_transcript.md (offline, deterministic)."""
from __future__ import annotations

from src import settings
from src.agents.orchestrator import ask
from src.security.auth import Principal

FLOW = [
    ("00:00", "Open the Executive Command Center", None),
    ("01:00", "Ask the copilot", "How much AI value have we actually realised?"),
    ("01:45", "Ask why", "Why is realised value below expectation?"),
    ("02:30", "Drill into the largest contributor", "Why did AI ROI decline this quarter?"),
    ("03:00", "Evidence: source → calculation → assumption → confidence", "Explain the $49.5M expected benefit."),
    ("03:30", "Scenario simulator", "What happens if infrastructure utilisation increases from 63% to 80%?"),
    ("04:15", "CFO briefing", "Prepare a CFO briefing."),
    ("extra", "Natural language to data", "Show AI investments above $5M."),
    ("extra", "Public HPE portfolio (RAG with citations)", "What is HPE's AI backlog?"),
]


def main() -> None:
    p = Principal("demo@meridian.example", "CFO")
    out = ["# Demo transcript", "", "*Machine-generated by `python -m scripts.run_demo` (offline mode, deterministic narrative). "
           f"{settings.SYNTHETIC_LABEL}.*", ""]
    for t, step, q in FLOW:
        out.append(f"## {t} · {step}")
        if not q:
            out += ["", "The CFO sees ten KPI tiles, the value bridge, the realised / validated / hypothetical split and the at-risk list.", ""]
            continue
        r = ask(q, p, use_llm=False)
        out += ["", f"> **CFO:** {q}", "", f"**ANSWER** ({r['agent']}, confidence {r['confidence']['level']}): {r['answer']}", "",
                "**KEY DRIVERS**", ""] + [f"- {d}" for d in r["key_drivers"][:6]] + ["", "**NUMBERS**", ""]
        out += [f"- {n['label']}: {n['display']} *({n['basis']})*" for n in r["numbers"][:8]]
        if r.get("query"):
            out += ["", "**GENERATED QUERY**", "", "```sql", r["query"]["sql"], "```", f"params: `{r['query']['params']}`"]
        out += ["", "**EVIDENCE**", ""] + [f"- {e['label']} (`{e['ref']}`)" + (f" <{e['url']}>" if e.get("url") else "") for e in r["evidence"][:5]]
        if r["assumptions"]:
            out += ["", "**ASSUMPTIONS**", ""] + [f"- {a['assumption_id']}: {a['description']}" for a in r["assumptions"][:5]]
        out += ["", f"**CONFIDENCE**: {r['confidence']['level']}. {r['confidence']['basis']}", "",
                "**DRILL-DOWN**: " + ", ".join(d["label"] for d in r["drilldown"][:5]), "", f"*audit #{r['audit_id']} · sha256 {r['result_sha256'][:16]}…*", ""]
    (settings.DOCS_DIR / "demo_transcript.md").write_text("\n".join(out) + "\n")
    print("wrote docs/demo_transcript.md")


if __name__ == "__main__":
    main()
